In [7]:
import numpy as np
import pandas as pd

In [4]:
sentence = 'Taclḥiyt nɣ Taclḥit nɣ Tasusit tga yat tutlayt tamaziɣt illan ɣ lmɣrib, middn li sis isawaln gan Iclḥiyn.'
token_sequence = str.split(sentence)
vocab = sorted(set(token_sequence))
# ', '.join(vocab)
num_tokens = len(token_sequence)
vocab_size = len(vocab)
onehot_vectors = np.zeros((
    num_tokens,
    vocab_size), int)
for i, word in enumerate(token_sequence):
    onehot_vectors[i, vocab.index(word)] = 1

In [10]:
df = pd.DataFrame(onehot_vectors, columns=vocab)
df[df==0]=' '
df

,Iclḥiyn.,Taclḥit,Taclḥiyt,Tasusit,gan,illan,isawaln,li,"lmɣrib,",middn,nɣ,sis,tamaziɣt,tga,tutlayt,yat,ɣ
0,,,1,,,,,,,,,,,,,,
1,,,,,,,,,,,1,,,,,,
2,,1,,,,,,,,,,,,,,,
3,,,,,,,,,,,1,,,,,,
4,,,,1,,,,,,,,,,,,,
5,,,,,,,,,,,,,,1,,,
6,,,,,,,,,,,,,,,,1,
7,,,,,,,,,,,,,,,1,,
8,,,,,,,,,,,,,1,,,,
9,,,,,,1,,,,,,,,,,,
10,,,,,,,,,,,,,,,,,1
11,,,,,,,,,1,,,,,,,,
12,,,,,,,,,,1,,,,,,,
13,,,,,,,,1,,,,,,,,,
14,,,,,,,,,,,,1,,,,,
15,,,,,,,1,,,,,,,,,,
16,,,,,1,,,,,,,,,,,,
17,1,,,,,,,,,,,,,,,,

In [19]:
sentence_bow = {}
for token in sentence.split():
    sentence_bow[token] = 1
sorted(sentence_bow.items())

[('Iclḥiyn.', 1),
 ('Taclḥit', 1),
 ('Taclḥiyt', 1),
 ('Tasusit', 1),
 ('gan', 1),
 ('illan', 1),
 ('isawaln', 1),
 ('li', 1),
 ('lmɣrib,', 1),
 ('middn', 1),
 ('nɣ', 1),
 ('sis', 1),
 ('tamaziɣt', 1),
 ('tga', 1),
 ('tutlayt', 1),
 ('yat', 1),
 ('ɣ', 1)]

In [21]:
df = pd.DataFrame(pd.Series(dict([(token, 1) for token in sentence.split()])), columns=['sent']).T
df

,Taclḥiyt,nɣ,Taclḥit,Tasusit,tga,yat,tutlayt,tamaziɣt,illan,ɣ,"lmɣrib,",middn,li,sis,isawaln,gan,Iclḥiyn.
sent,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [42]:
sentences = """Tettusawal Tclḥit ɣ Sus, Iḥaḥan, Lḥuz n Mṛṛakc d kra n tsggʷin yaḍnin asn d iwalan.\n"""
sentences += """Tumẓ tutlayt taclḥit zɣ Taṣṣurt ɣ ugafa ar Agʷlmim ɣ unẓul ar Warzazat ɣ ugmuḍ.\n"""
sentences += """Mac ar tt inn nttafa tlla ula ɣ timdinin mqqurnin n Lmɣrib zun d Tigmmi Tumlilt (kaẓa), d Ṛṛbaḍ d Sla.\n"""
sentences += """Tkka tt inn tclḥiyt ar tettyura s uskkil aɛrab, ilin sis kigan n warratn iclḥiyn."""
corpus = {}
for i, sent in enumerate(sentences.split('\n')):
    corpus['sent{}'.format(i)] = dict((tok, 1) for tok in sent.split())

df = pd.DataFrame.from_records(corpus).fillna(0).astype(int).T
df[df.columns[:10]]

       Tettusawal  Tclḥit  ɣ  Sus,  Iḥaḥan,  Lḥuz  n  Mṛṛakc  d  kra
sent0           1       1  1     1        1     1  1       1  1    1
sent1           0       0  1     0        0     0  0       0  0    0
sent2           0       0  1     0        0     0  1       0  1    0
sent3           0       0  0     0        0     0  1       0  0    0

In [62]:
v1 = np.array([1,2,3])
v2 = np.array([2,3,4])
v1.dot(v2)
df = df.T

In [75]:
df.sent0.dot(df.sent3)

1

In [76]:
[(k, v) for (k, v) in (df.sent0 & df.sent3).items() if v]

[('n', 1)]

In [84]:
# The plus sign after the closing
# square bracket ( ] ) means that a match must contain one or more of the characters
# inside the square brackets.

import re
sentence = """Ar ass-ad ur illi kra n uṣiḍn igaddan ittuyskarn f imsiwln n tutlayin timaziɣin ɣ tmazirt n Lmɣrib."""
tokens = re.split(r'[-\s.,;!?]+', sentence)
tokens

['Ar',
 'ass',
 'ad',
 'ur',
 'illi',
 'kra',
 'n',
 'uṣiḍn',
 'igaddan',
 'ittuyskarn',
 'f',
 'imsiwln',
 'n',
 'tutlayin',
 'timaziɣin',
 'ɣ',
 'tmazirt',
 'n',
 'Lmɣrib',
 '']

In [86]:
pattern = re.compile(r'[-\s.,;!?]+')
tokens = pattern.split(sentence)
tokens

['Ar',
 'ass',
 'ad',
 'ur',
 'illi',
 'kra',
 'n',
 'uṣiḍn',
 'igaddan',
 'ittuyskarn',
 'f',
 'imsiwln',
 'n',
 'tutlayin',
 'timaziɣin',
 'ɣ',
 'tmazirt',
 'n',
 'Lmɣrib',
 '']

In [92]:
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer(r'\w+|$[0-9.]+|\S+-')
tokenizer.tokenize(sentence)

['Ar',
 'ass',
 'ad',
 'ur',
 'illi',
 'kra',
 'n',
 'uṣiḍn',
 'igaddan',
 'ittuyskarn',
 'f',
 'imsiwln',
 'n',
 'tutlayin',
 'timaziɣin',
 'ɣ',
 'tmazirt',
 'n',
 'Lmɣrib']

In [94]:
# Treebank Tokenizer
from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()
tokenizer.tokenize(sentence)

['Ar',
 'ass-ad',
 'ur',
 'illi',
 'kra',
 'n',
 'uṣiḍn',
 'igaddan',
 'ittuyskarn',
 'f',
 'imsiwln',
 'n',
 'tutlayin',
 'timaziɣin',
 'ɣ',
 'tmazirt',
 'n',
 'Lmɣrib',
 '.']

In [13]:
from config.placeholders import *
import os
import PyPDF2


path = os.path.join(TRAINING_RESOURCES_DIR, 'shilha_bible.pdf')
file = open(path, 'rb')
fileReader = PyPDF2.PdfFileReader(file)

In [21]:
page = fileReader.getPage(50)
page.getContents()

{'/Filter': '/FlateDecode'}

'/home/ayoub/projects/inna/doc/training'